# -*- coding: utf-8 -*-
"""Reliability Aware Fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dl-3uXhUBjCyOvUuTXO_xwcc1W0mfx2e
"""

import os
from google.colab import drive
drive.mount('/content/drive')

SAVE_DIR = "/content/drive/MyDrive/rs_revision_phase3"
FIG_DIR = f"{SAVE_DIR}/figures"
os.makedirs(SAVE_DIR, exist_ok=True)
os.makedirs(FIG_DIR, exist_ok=True)

os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

import torch
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.use_deterministic_algorithms(True, warn_only=True)

print("PyTorch:", torch.__version__)
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE - set T4 runtime!")
print("Save dir:", SAVE_DIR)

!pip -q install kagglehub pillow scikit-learn tqdm pandas matplotlib

import kagglehub
from pathlib import Path

dataset_path = kagglehub.dataset_download("requiemonk/sentinel12-image-pairs-segregated-by-terrain")
dataset_root = Path(dataset_path)
print("Dataset at:", dataset_root)

from collections import Counter

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}

def normalized_name(name):
    return name.lower().replace("_", "").replace("-", "").replace(" ", "")

all_images = [p for p in dataset_root.rglob("*") if p.suffix.lower() in IMAGE_EXTS]

def modality_from_path(path):
    parts = [normalized_name(part) for part in path.relative_to(dataset_root).parts]
    if any(part in {"sar", "s1", "sentinel1"} for part in parts):
        return "radar"
    if any(part in {"opt", "optical", "s2", "sentinel2", "rgb"} for part in parts):
        return "optical"
    return "unknown"

def pair_key(path):
    stem = path.stem
    for a, b in [("_s1_", "_sx_"), ("_s2_", "_sx_"), ("-s1-", "-sx-"), ("-s2-", "-sx-")]:
        stem = stem.replace(a, b)
    return stem

def label_from_path(path):
    known = ["agri", "barrenland", "grassland", "urban"]
    for part in path.relative_to(dataset_root).parts:
        if normalized_name(part) in known:
            return normalized_name(part)
    return "unknown"

records = [{"path": p, "modality": modality_from_path(p),
            "label": label_from_path(p), "stem": pair_key(p)} for p in all_images]

radar_records = [r for r in records if r["modality"] == "radar"]
optical_records = [r for r in records if r["modality"] == "optical"]
optical_by_key = {(r["label"], r["stem"]): r["path"] for r in optical_records}

pairs = []
for r in radar_records:
    key = (r["label"], r["stem"])
    if key in optical_by_key:
        pairs.append((r["path"], optical_by_key[key], r["label"]))

if len(pairs) == 0:  # fallback: pair by sorted order within label
    for label in sorted({r["label"] for r in records if r["label"] != "unknown"}):
        rp = sorted(r["path"] for r in radar_records if r["label"] == label)
        op = sorted(r["path"] for r in optical_records if r["label"] == label)
        pairs.extend(zip(rp, op, [label] * min(len(rp), len(op))))

print("Total pairs:", len(pairs))
print("Class counts:", Counter(lbl for _, _, lbl in pairs))
assert len(pairs) > 0, "No pairs found - send me this cell's output."

import random
import numpy as np
import pandas as pd
from PIL import Image
from torch import nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
IMAGE_SIZE = 128
BATCH_SIZE = 32
CLASS_NAMES = sorted({lbl for _, _, lbl in pairs})   # ['agri','barrenland','grassland','urban']
class_to_idx = {c: i for i, c in enumerate(CLASS_NAMES)}
NUM_CLASSES = len(CLASS_NAMES)
REP_SEED = 2026                                       # representative seed
print("Classes:", class_to_idx)

def set_all_seeds(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def pil_to_tensor(image, mode):
    image = image.convert(mode).resize((IMAGE_SIZE, IMAGE_SIZE))
    arr = np.array(image).astype("float32") / 255.0
    arr = arr[None, :, :] if arr.ndim == 2 else np.transpose(arr, (2, 0, 1))
    t = torch.from_numpy(arr)
    mean = t.mean(dim=(1, 2), keepdim=True)
    std = t.std(dim=(1, 2), keepdim=True).clamp_min(1e-6)
    return (t - mean) / std

class Sentinel12PairDataset(Dataset):
    def __init__(self, pair_list):
        self.pair_list = pair_list
    def __len__(self):
        return len(self.pair_list)
    def __getitem__(self, idx):
        s1, s2, label = self.pair_list[idx]
        radar = pil_to_tensor(Image.open(s1), "L")
        optical = pil_to_tensor(Image.open(s2), "RGB")
        return radar, optical, torch.tensor(class_to_idx[label], dtype=torch.long)

def make_loaders(pair_list, seed):
    tr, va = train_test_split(pair_list, test_size=0.2, random_state=seed,
                              stratify=[l for _, _, l in pair_list])
    tr_loader = DataLoader(Sentinel12PairDataset(tr), batch_size=BATCH_SIZE,
                           shuffle=True, num_workers=0)
    va_loader = DataLoader(Sentinel12PairDataset(va), batch_size=BATCH_SIZE,
                           shuffle=False, num_workers=0)
    return tr_loader, va_loader, tr, va

def degrade_optical(optical, mode="clean"):
    if mode == "clean":
        return optical
    x = optical.clone()
    if mode == "noise":
        return x + torch.randn_like(x) * 0.95
    if mode == "heavy_noise":
        return x + torch.randn_like(x) * 1.45
    if mode == "channel_drop":
        mask = (torch.rand(x.shape[0], x.shape[1], 1, 1, device=x.device) > 0.35).float()
        return x * mask
    if mode == "cloud_mask":
        _, _, h, w = x.shape
        mh, mw = int(h * 0.45), int(w * 0.45)
        for i in range(x.shape[0]):
            top = torch.randint(0, h - mh + 1, (1,), device=x.device).item()
            left = torch.randint(0, w - mw + 1, (1,), device=x.device).item()
            x[i, :, top:top + mh, left:left + mw] = 0
        return x
    if mode == "mixed":
        x = x + torch.randn_like(x) * 0.75
        mask = (torch.rand(x.shape[0], x.shape[1], 1, 1, device=x.device) > 0.20).float()
        return x * mask
    raise ValueError(mode)

# Training-time menus (as described in the manuscript)
def train_degradation_fusion_baseline(optical):   # for early/feature/logit fusion models
    return degrade_optical(optical, random.choice(
        ["clean", "clean", "noise", "channel_drop", "cloud_mask"]))

def train_degradation_proposed(optical):          # for the proposed model (Sec. 2.7)
    return degrade_optical(optical, random.choice(
        ["clean", "noise", "noise", "heavy_noise", "channel_drop", "cloud_mask", "mixed"]))

SETTINGS4 = ["clean", "noise", "channel_drop", "cloud_mask"]
SETTINGS6 = ["clean", "noise", "heavy_noise", "channel_drop", "cloud_mask", "mixed"]
EVAL_SEED = {s: 9000 + i for i, s in enumerate(SETTINGS6)}  # reproducible degradation draws

class SmallEncoder(nn.Module):
    def __init__(self, in_channels, feature_dim=128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_channels, 32, 3, padding=1), nn.BatchNorm2d(32),
            nn.ReLU(inplace=True), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64),
            nn.ReLU(inplace=True), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128),
            nn.ReLU(inplace=True), nn.AdaptiveAvgPool2d(1),
        )
        self.proj = nn.Linear(128, feature_dim)
    def forward(self, x):
        return self.proj(self.net(x).flatten(1))

class SingleModalityClassifier(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.encoder = SmallEncoder(in_channels)
        self.classifier = nn.Linear(128, NUM_CLASSES)
    def forward(self, x):
        return self.classifier(self.encoder(x))

class EarlyFusionClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = SmallEncoder(4)
        self.classifier = nn.Linear(128, NUM_CLASSES)
    def forward(self, radar, optical):
        return self.classifier(self.encoder(torch.cat([radar, optical], dim=1)))

class FeatureFusionClassifier(nn.Module):          # feature-level fusion variant
    def __init__(self):
        super().__init__()
        self.radar_encoder = SmallEncoder(1)
        self.optical_encoder = SmallEncoder(3)
        self.gate = nn.Sequential(nn.Linear(256, 128), nn.ReLU(inplace=True),
                                  nn.Linear(128, 2), nn.Softmax(dim=1))
        self.classifier = nn.Linear(128, NUM_CLASSES)
    def forward(self, radar, optical):
        rf, of = self.radar_encoder(radar), self.optical_encoder(optical)
        w = self.gate(torch.cat([rf, of], dim=1))
        return self.classifier(w[:, 0:1] * rf + w[:, 1:2] * of)

class LogitFusionClassifier(nn.Module):            # logit-level fusion variant
    def __init__(self, feature_dim=128):
        super().__init__()
        self.radar_encoder = SmallEncoder(1, feature_dim)
        self.optical_encoder = SmallEncoder(3, feature_dim)
        self.radar_head = nn.Linear(feature_dim, NUM_CLASSES)
        self.optical_head = nn.Linear(feature_dim, NUM_CLASSES)
        self.gate = nn.Sequential(nn.Linear(feature_dim * 2, feature_dim),
                                  nn.ReLU(inplace=True), nn.Dropout(0.15),
                                  nn.Linear(feature_dim, 2), nn.Softmax(dim=1))
    def forward(self, radar, optical, return_all=False):
        rf, of = self.radar_encoder(radar), self.optical_encoder(optical)
        rl, ol = self.radar_head(rf), self.optical_head(of)
        w = self.gate(torch.cat([rf, of], dim=1))
        fused = w[:, 0:1] * rl + w[:, 1:2] * ol
        return (fused, w, rl, ol) if return_all else fused

def confidence_features(logits):
    probs = torch.softmax(logits, dim=1)
    top2 = torch.topk(probs, k=2, dim=1).values
    entropy = -(probs * probs.clamp_min(1e-8).log()).sum(dim=1, keepdim=True) / np.log(NUM_CLASSES)
    return torch.cat([top2[:, 0:1], top2[:, 0:1] - top2[:, 1:2], entropy], dim=1)

def optical_quality_features(optical):
    return torch.cat([
        optical.abs().mean(dim=(1, 2, 3)).view(-1, 1),
        optical.std(dim=(1, 2, 3)).view(-1, 1),
        (optical.abs() < 1e-6).float().mean(dim=(1, 2, 3)).view(-1, 1),
        (optical.abs() > 2.5).float().mean(dim=(1, 2, 3)).view(-1, 1),
    ], dim=1)

class ProposedFusionClassifier(nn.Module):         # reliability-aware fusion (proposed)
    def __init__(self, feature_dim=128):
        super().__init__()
        self.radar_encoder = SmallEncoder(1, feature_dim)
        self.optical_encoder = SmallEncoder(3, feature_dim)
        self.radar_head = nn.Linear(feature_dim, NUM_CLASSES)
        self.optical_head = nn.Linear(feature_dim, NUM_CLASSES)
        self.gate = nn.Sequential(
            nn.Linear(feature_dim * 2 + 10, 128), nn.ReLU(inplace=True), nn.Dropout(0.20),
            nn.Linear(128, 64), nn.ReLU(inplace=True),
            nn.Linear(64, 2), nn.Softmax(dim=1))
    def forward(self, radar, optical, return_all=False):
        rf, of = self.radar_encoder(radar), self.optical_encoder(optical)
        rl, ol = self.radar_head(rf), self.optical_head(of)
        gate_in = torch.cat([rf, of, confidence_features(rl),
                             confidence_features(ol), optical_quality_features(optical)], dim=1)
        w = self.gate(gate_in)
        fused = w[:, 0:1] * rl + w[:, 1:2] * ol
        return (fused, w, rl, ol) if return_all else fused

MODEL_BUILDERS = {
    "radar": lambda: SingleModalityClassifier(1),
    "optical": lambda: SingleModalityClassifier(3),
    "early_fusion": EarlyFusionClassifier,
    "feature_fusion": FeatureFusionClassifier,
    "logit_fusion": LogitFusionClassifier,
    "proposed": ProposedFusionClassifier,
}
GATED = {"logit_fusion", "proposed"}

def forward_any(model, name, radar, optical):
    if name == "radar":
        return model(radar)
    if name == "optical":
        return model(optical)
    return model(radar, optical)

def train_epoch(model, name, loader, optimizer, criterion):
    model.train()
    total = 0.0
    aux = 0.45 if name == "proposed" else (0.35 if name == "logit_fusion" else 0.0)
    for radar, optical, labels in tqdm(loader, leave=False):
        radar, optical, labels = radar.to(DEVICE), optical.to(DEVICE), labels.to(DEVICE)
        if name == "proposed":
            optical = train_degradation_proposed(optical)
        elif name in ["early_fusion", "feature_fusion", "logit_fusion"]:
            optical = train_degradation_fusion_baseline(optical)
        optimizer.zero_grad(set_to_none=True)
        if name in GATED:
            fused, w, rl, ol = model(radar, optical, return_all=True)
            loss = criterion(fused, labels) + aux * criterion(rl, labels) + aux * criterion(ol, labels)
        else:
            loss = criterion(forward_any(model, name, radar, optical), labels)
        loss.backward()
        optimizer.step()
        total += loss.item() * labels.shape[0]
    return total / len(loader.dataset)

@torch.no_grad()
def evaluate(model, name, loader, setting="clean"):
    """Reproducible evaluation: degradation draws are seeded per setting."""
    model.eval()
    torch.manual_seed(EVAL_SEED[setting])
    correct, total, weights = 0, 0, []
    for radar, optical, labels in tqdm(loader, leave=False):
        radar, optical, labels = radar.to(DEVICE), optical.to(DEVICE), labels.to(DEVICE)
        optical = degrade_optical(optical, setting)
        if name in GATED:
            logits, w, _, _ = model(radar, optical, return_all=True)
            weights.append(w.cpu())
        else:
            logits = forward_any(model, name, radar, optical)
        correct += (logits.argmax(dim=1) == labels).sum().item()
        total += labels.numel()
    out = {"accuracy": correct / total}
    if weights:
        w = torch.cat(weights)
        out["avg_radar_weight"] = w[:, 0].mean().item()
        out["avg_optical_weight"] = w[:, 1].mean().item()
    return out

def load_or_none(name, tag):
    path = f"{SAVE_DIR}/{name}_{tag}.pt"
    if os.path.exists(path):
        model = MODEL_BUILDERS[name]().to(DEVICE)
        model.load_state_dict(torch.load(path, map_location=DEVICE))
        model.eval()
        print(f"Loaded existing checkpoint: {path}")
        return model
    return None

print("Setup complete.")

# Setup SEED-2026 RUN
TRAIN_PLAN = {  # name: (epochs, lr)
    "radar": (10, 1e-3),
    "optical": (10, 1e-3),
    "early_fusion": (10, 1e-3),
    "feature_fusion": (10, 1e-3),
    "logit_fusion": (15, 1e-3),
}

tr_loader, va_loader, tr_pairs_rep, va_pairs_rep = make_loaders(pairs, REP_SEED)
print(f"Split: {len(tr_pairs_rep)} train / {len(va_pairs_rep)} val")

table2_rows = []
for name, (epochs, lr) in TRAIN_PLAN.items():
    model = load_or_none(name, f"seed{REP_SEED}")
    if model is None:
        print(f"\n=== Training {name} ===")
        set_all_seeds(REP_SEED)
        tr_loader, va_loader, _, _ = make_loaders(pairs, REP_SEED)  # rebuild for identical shuffling
        model = MODEL_BUILDERS[name]().to(DEVICE)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
        for epoch in range(1, epochs + 1):
            loss = train_epoch(model, name, tr_loader, optimizer, criterion)
            print(f"{name} epoch={epoch} loss={loss:.4f}")
        torch.save(model.state_dict(), f"{SAVE_DIR}/{name}_seed{REP_SEED}.pt")
    for setting in SETTINGS4:
        r = evaluate(model, name, va_loader, setting)
        r.update({"model": name, "setting": setting})
        table2_rows.append(r)
        print(name, setting, round(r["accuracy"], 4))

pd.DataFrame(table2_rows).to_csv(f"{SAVE_DIR}/new_table2_baselines.csv", index=False)
print("Saved new_table2_baselines.csv")

model = load_or_none("proposed", f"seed{REP_SEED}")
if model is None:
    print("=== Training proposed model (seed 2026, balanced selection) ===")
    set_all_seeds(REP_SEED)
    tr_loader, va_loader, _, _ = make_loaders(pairs, REP_SEED)
    model = ProposedFusionClassifier().to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=8e-4, weight_decay=1e-4)
    best_score, best_state, best_epoch = -1.0, None, None
    for epoch in range(1, 16):
        loss = train_epoch(model, "proposed", tr_loader, optimizer, criterion)
        evals = {s: evaluate(model, "proposed", va_loader, s)["accuracy"] for s in SETTINGS4}
        score = sum(evals.values()) / 4
        if score > best_score:
            best_score, best_epoch = score, epoch
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        print(f"epoch={epoch} loss={loss:.4f} score={score:.4f} " +
              " ".join(f"{k}={v:.4f}" for k, v in evals.items()))
    model.load_state_dict(best_state)
    torch.save(best_state, f"{SAVE_DIR}/proposed_seed{REP_SEED}.pt")
    torch.save(best_state, f"{SAVE_DIR}/balanced_model_seed2026.pt")  # authoritative copy
    print(f"AUTHORITATIVE checkpoint saved (best epoch {best_epoch}, score {best_score:.5f})")

_, va_loader, _, va_pairs_rep = make_loaders(pairs, REP_SEED)
rows = []
for s in SETTINGS6:
    r = evaluate(model, "proposed", va_loader, s)
    r.update({"model": "proposed", "setting": s, "seed": REP_SEED})
    rows.append(r)
    print(s, r)
pd.DataFrame(rows).to_csv(f"{SAVE_DIR}/new_table3_4_proposed_seed{REP_SEED}.csv", index=False)
print("Saved new_table3_4_proposed CSV — SEND THIS OUTPUT BACK before we edit the manuscript.")

SEEDS = [7, 42, 123, 777, 2026]

def run_proposed_seed(seed):
    ckpt = f"{SAVE_DIR}/proposed_seed{seed}.pt"
    csvp = f"{SAVE_DIR}/multiseed_proposed_seed{seed}.csv"
    if os.path.exists(csvp):
        print(f"seed {seed}: done, loading CSV")
        return pd.read_csv(csvp)
    set_all_seeds(seed)
    trl, val, _, _ = make_loaders(pairs, seed)
    if os.path.exists(ckpt):
        m = ProposedFusionClassifier().to(DEVICE)
        m.load_state_dict(torch.load(ckpt, map_location=DEVICE))
    else:
        print(f"\n=== Training proposed model, seed {seed} ===")
        m = ProposedFusionClassifier().to(DEVICE)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.AdamW(m.parameters(), lr=8e-4, weight_decay=1e-4)
        best_score, best_state = -1.0, None
        for epoch in range(1, 16):
            loss = train_epoch(m, "proposed", trl, optimizer, criterion)
            evals = {s: evaluate(m, "proposed", val, s)["accuracy"] for s in SETTINGS4}
            score = sum(evals.values()) / 4
            if score > best_score:
                best_score = score
                best_state = {k: v.detach().cpu().clone() for k, v in m.state_dict().items()}
            print(f"seed={seed} epoch={epoch} loss={loss:.4f} score={score:.4f}")
        m.load_state_dict(best_state)
        torch.save(best_state, ckpt)
    rows = []
    for s in SETTINGS6:
        r = evaluate(m, "proposed", val, s)
        r.update({"seed": seed, "setting": s})
        rows.append(r)
    df = pd.DataFrame(rows)
    df.to_csv(csvp, index=False)
    return df

multiseed = pd.concat([run_proposed_seed(s) for s in SEEDS], ignore_index=True)
multiseed.to_csv(f"{SAVE_DIR}/multiseed_all.csv", index=False)
print("Seeds completed:", sorted(multiseed['seed'].unique()))

def run_baseline_seed(name, seed, epochs, lr):
    csvp = f"{SAVE_DIR}/multiseed_{name}_seed{seed}.csv"
    if os.path.exists(csvp):
        print(f"{name} seed {seed}: done"); return pd.read_csv(csvp)
    set_all_seeds(seed)
    trl, val, _, _ = make_loaders(pairs, seed)
    m = MODEL_BUILDERS[name]().to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(m.parameters(), lr=lr, weight_decay=1e-4)
    for epoch in range(1, epochs + 1):
        loss = train_epoch(m, name, trl, optimizer, criterion)
        print(f"{name} seed={seed} epoch={epoch} loss={loss:.4f}")
    torch.save(m.state_dict(), f"{SAVE_DIR}/{name}_seed{seed}_ms.pt")
    rows = []
    for s in SETTINGS4:
        r = evaluate(m, name, val, s); r.update({"seed": seed, "setting": s, "model": name})
        rows.append(r)
    df = pd.DataFrame(rows); df.to_csv(csvp, index=False); return df

SEEDS = [7, 42, 123, 777, 2026]
ms_base = pd.concat(
    [run_baseline_seed("logit_fusion", s, 15, 1e-3) for s in SEEDS] +
    [run_baseline_seed("optical", s, 10, 1e-3) for s in SEEDS], ignore_index=True)
ms_base.to_csv(f"{SAVE_DIR}/multiseed_baselines.csv", index=False)

for name in ["logit_fusion", "optical"]:
    sub = ms_base[ms_base.model == name].pivot(index="seed", columns="setting", values="accuracy")[SETTINGS4]
    print(f"\n{name} across seeds:")
    for s in SETTINGS4:
        print(f"  {s}: {sub[s].mean():.4f} ± {sub[s].std(ddof=1):.4f}")

acc = multiseed.pivot(index="seed", columns="setting", values="accuracy")[SETTINGS6]
sarw = multiseed.pivot(index="seed", columns="setting", values="avg_radar_weight")[SETTINGS6]
print("Per-seed accuracy:")
display(acc.round(4))

print("\n| Setting | Mean Acc. | Std. | Mean SAR weight | SAR weight Std. |")
print("| --- | ---: | ---: | ---: | ---: |")
for s in SETTINGS6:
    print(f"| {s} | {acc[s].mean():.4f} | {acc[s].std(ddof=1):.4f} "
          f"| {sarw[s].mean():.4f} | {sarw[s].std(ddof=1):.4f} |")

models = {}
for name in ["radar", "optical", "early_fusion", "feature_fusion", "logit_fusion", "proposed"]:
    models[name] = load_or_none(name, f"seed{REP_SEED}")
    assert models[name] is not None, f"Missing checkpoint for {name} - run Section A first."
_, va_loader, _, va_pairs_rep = make_loaders(pairs, REP_SEED)
val_ds = Sentinel12PairDataset(va_pairs_rep)
print("All six models loaded.")

from sklearn.metrics import f1_score, confusion_matrix
import matplotlib.pyplot as plt

@torch.no_grad()
def predict_all(model, name, loader, setting):
    model.eval()
    torch.manual_seed(EVAL_SEED[setting])
    preds, labels_all, ws = [], [], []
    for radar, optical, labels in tqdm(loader, leave=False):
        radar, optical = radar.to(DEVICE), optical.to(DEVICE)
        optical = degrade_optical(optical, setting)
        if name in GATED:
            logits, w, _, _ = model(radar, optical, return_all=True)
            ws.append(w.cpu())
        else:
            logits = forward_any(model, name, radar, optical)
        preds.append(logits.argmax(dim=1).cpu())
        labels_all.append(labels)
    preds = torch.cat(preds).numpy()
    labels_all = torch.cat(labels_all).numpy()
    ws = torch.cat(ws).numpy() if ws else None
    return preds, labels_all, ws

table5_rows, cms = [], {}
for s in SETTINGS6:
    preds, labs, _ = predict_all(models["proposed"], "proposed", va_loader, s)
    per = f1_score(labs, preds, average=None)
    table5_rows.append({"setting": s, "macro_f1": f1_score(labs, preds, average="macro"),
                        **{f"f1_{c}": v for c, v in zip(CLASS_NAMES, per)}})
    cms[s] = confusion_matrix(labs, preds)
t5 = pd.DataFrame(table5_rows).round(4)
display(t5)
t5.to_csv(f"{SAVE_DIR}/new_table5_perclass_f1.csv", index=False)

for s in ["clean", "noise", "heavy_noise"]:
    fig, ax = plt.subplots(figsize=(5, 4.2))
    im = ax.imshow(cms[s], cmap="Blues")
    for i in range(NUM_CLASSES):
        for j in range(NUM_CLASSES):
            ax.text(j, i, cms[s][i, j], ha="center", va="center",
                    color="white" if cms[s][i, j] > cms[s].max() / 2 else "black")
    ax.set_xticks(range(NUM_CLASSES), CLASS_NAMES, rotation=30)
    ax.set_yticks(range(NUM_CLASSES), CLASS_NAMES)
    ax.set_xlabel("Predicted"); ax.set_ylabel("True")
    ax.set_title(f"Confusion matrix - {s} (seed {REP_SEED})")
    fig.colorbar(im); fig.tight_layout()
    fig.savefig(f"{FIG_DIR}/confusion_{s}.png", dpi=300)
    plt.show()

gate_summary = []
for s in SETTINGS6:
    preds, labs, ws = predict_all(models["proposed"], "proposed", va_loader, s)
    sar_w = ws[:, 0]
    correct = preds == labs
    row = {"setting": s, "sar_w_mean": sar_w.mean(), "sar_w_std": sar_w.std(),
           "sar_w_correct": sar_w[correct].mean(), "sar_w_incorrect": sar_w[~correct].mean()
           if (~correct).any() else np.nan}
    for ci, c in enumerate(CLASS_NAMES):
        row[f"sar_w_{c}"] = sar_w[labs == ci].mean()
    gate_summary.append(row)
    if s == "clean":
        clean_ws, clean_labs, clean_preds = sar_w, labs, preds

gs = pd.DataFrame(gate_summary).round(4)
display(gs)
gs.to_csv(f"{SAVE_DIR}/gate_analysis.csv", index=False)

# Distribution figure (not just averages)
fig, ax = plt.subplots(figsize=(9, 4.5))
data = []
for s in SETTINGS6:
    preds, labs, ws = predict_all(models["proposed"], "proposed", va_loader, s)
    data.append(ws[:, 0])
ax.violinplot(data, showmeans=True)
ax.axhline(0.5, ls="--", c="gray", lw=1, label="Equal weighting")
ax.set_xticks(range(1, len(SETTINGS6) + 1), SETTINGS6, rotation=20)
ax.set_ylabel("Per-sample SAR weight")
ax.set_title(f"Distribution of learned SAR weights (seed {REP_SEED})")
ax.legend(); fig.tight_layout()
fig.savefig(f"{FIG_DIR}/gate_weight_distributions.png", dpi=300)
plt.show()

# Simple calibration check: does the gate give optical more weight when the optical branch is right?
@torch.no_grad()
def branch_correct_vs_weight(setting):
    torch.manual_seed(EVAL_SEED[setting])
    opt_correct, opt_w = [], []
    for radar, optical, labels in tqdm(va_loader, leave=False):
        radar, optical = radar.to(DEVICE), optical.to(DEVICE)
        optical = degrade_optical(optical, setting)
        _, w, rl, ol = models["proposed"](radar, optical, return_all=True)
        opt_correct.append((ol.argmax(1).cpu() == labels).numpy())
        opt_w.append(w[:, 1].cpu().numpy())
    oc, ow = np.concatenate(opt_correct), np.concatenate(opt_w)
    print(f"{setting}: optical weight when optical-branch CORRECT = {ow[oc].mean():.3f}, "
          f"when WRONG = {ow[~oc].mean():.3f}  (n_wrong={( ~oc).sum()})")

for s in ["clean", "noise", "channel_drop"]:
    branch_correct_vs_weight(s)

def raw_images(pair):  # unnormalized, for display
    s1, s2, label = pair
    return (np.array(Image.open(s1).convert("L").resize((IMAGE_SIZE, IMAGE_SIZE))),
            np.array(Image.open(s2).convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE))), label)

# Figure A: example SAR/optical pair per class
fig, axes = plt.subplots(NUM_CLASSES, 4, figsize=(9, 2.3 * NUM_CLASSES))
for ci, c in enumerate(CLASS_NAMES):
    examples = [p for p in va_pairs_rep if p[2] == c][:2]
    for k, ex in enumerate(examples):
        sar, opt, _ = raw_images(ex)
        axes[ci, 2 * k].imshow(sar, cmap="gray"); axes[ci, 2 * k].set_title(f"{c} - SAR", fontsize=9)
        axes[ci, 2 * k + 1].imshow(opt); axes[ci, 2 * k + 1].set_title(f"{c} - optical", fontsize=9)
for ax in axes.ravel():
    ax.axis("off")
fig.tight_layout(); fig.savefig(f"{FIG_DIR}/class_examples.png", dpi=300); plt.show()

# Figure B: prediction gallery under degradation (correct AND incorrect examples)
@torch.no_grad()
def gallery(setting, n=8, prefer_errors=True):
    torch.manual_seed(EVAL_SEED[setting])
    idxs = list(range(0, len(va_pairs_rep), max(1, len(va_pairs_rep) // 400)))[:400]
    batch_r = torch.stack([val_ds[i][0] for i in idxs]).to(DEVICE)
    batch_o = torch.stack([val_ds[i][1] for i in idxs]).to(DEVICE)
    labs = np.array([val_ds[i][2].item() for i in idxs])
    deg_o = degrade_optical(batch_o, setting)
    logits, w, _, _ = models["proposed"](batch_r, deg_o, return_all=True)
    preds = logits.argmax(1).cpu().numpy()
    wrong = np.where(preds != labs)[0]
    right = np.where(preds == labs)[0]
    chosen = (list(wrong[: n // 2]) + list(right[: n - len(wrong[: n // 2])])) if prefer_errors else list(right[:n])
    fig, axes = plt.subplots(2, len(chosen), figsize=(2.1 * len(chosen), 4.6))
    for k, j in enumerate(chosen):
        sar, opt, _ = raw_images(va_pairs_rep[idxs[j]])
        do = deg_o[j].cpu()
        do = (do - do.min()) / (do.max() - do.min() + 1e-6)
        axes[0, k].imshow(do.permute(1, 2, 0).numpy()); axes[0, k].axis("off")
        ok = preds[j] == labs[j]
        axes[0, k].set_title(f"true:{CLASS_NAMES[labs[j]]}\npred:{CLASS_NAMES[preds[j]]}\nw_SAR={w[j,0]:.2f}",
                             fontsize=8, color="green" if ok else "red")
        axes[1, k].imshow(sar, cmap="gray"); axes[1, k].axis("off")
    axes[0, 0].set_ylabel("degraded optical"); axes[1, 0].set_ylabel("SAR")
    fig.suptitle(f"Proposed model predictions - {setting}")
    fig.tight_layout(); fig.savefig(f"{FIG_DIR}/gallery_{setting}.png", dpi=300); plt.show()

for s in ["clean", "noise", "channel_drop", "cloud_mask"]:
    gallery(s)

# Figure C: model comparison on the SAME degraded patches
@torch.no_grad()
def model_comparison(setting="noise", n=6):
    torch.manual_seed(EVAL_SEED[setting])
    idxs = list(range(0, 6 * 137, 137))[:n]
    br = torch.stack([val_ds[i][0] for i in idxs]).to(DEVICE)
    bo = torch.stack([val_ds[i][1] for i in idxs]).to(DEVICE)
    labs = [val_ds[i][2].item() for i in idxs]
    do = degrade_optical(bo, setting)
    names = ["optical", "early_fusion", "logit_fusion", "proposed"]
    preds = {}
    for nm in names:
        m = models[nm]
        out = m(do) if nm == "optical" else (m(br, do, return_all=True)[0] if nm in GATED else m(br, do))
        preds[nm] = out.argmax(1).cpu().numpy()
    fig, axes = plt.subplots(1, n, figsize=(2.2 * n, 3.4))
    for k, i in enumerate(idxs):
        img = do[k].cpu(); img = (img - img.min()) / (img.max() - img.min() + 1e-6)
        axes[k].imshow(img.permute(1, 2, 0).numpy()); axes[k].axis("off")
        lines = [f"true: {CLASS_NAMES[labs[k]]}"] + [
            f"{nm}: {CLASS_NAMES[preds[nm][k]]}{'  ok' if preds[nm][k]==labs[k] else '  X'}" for nm in names]
        axes[k].set_title("\n".join(lines), fontsize=7)
    fig.suptitle(f"Model comparison under {setting} degradation")
    fig.tight_layout(); fig.savefig(f"{FIG_DIR}/model_comparison_{setting}.png", dpi=300); plt.show()

model_comparison("noise"); model_comparison("cloud_mask")

import time

rows = []
sample_r = torch.randn(BATCH_SIZE, 1, IMAGE_SIZE, IMAGE_SIZE, device=DEVICE)
sample_o = torch.randn(BATCH_SIZE, 3, IMAGE_SIZE, IMAGE_SIZE, device=DEVICE)
for name, m in models.items():
    params = sum(p.numel() for p in m.parameters())
    with torch.no_grad():
        for _ in range(5):
            forward_any(m, name, sample_r, sample_o)
        torch.cuda.synchronize()
        t0 = time.time()
        for _ in range(50):
            forward_any(m, name, sample_r, sample_o)
        torch.cuda.synchronize()
        ms = (time.time() - t0) / 50 * 1000
    rows.append({"model": name, "parameters": params, "ms_per_batch32": round(ms, 2)})
cost = pd.DataFrame(rows)
display(cost)
cost.to_csv(f"{SAVE_DIR}/model_cost_table.csv", index=False)

t2 = pd.read_csv(f"{SAVE_DIR}/new_table2_baselines.csv")
t34 = pd.read_csv(f"{SAVE_DIR}/new_table3_4_proposed_seed{REP_SEED}.csv")
t2 = pd.concat([t2, t34[t34.setting.isin(SETTINGS4)][["model", "setting", "accuracy"]]])

LABELS = {"radar": "Radar-only", "optical": "Optical-only", "early_fusion": "Early Fusion",
          "feature_fusion": "Feature-Level Fusion Variant", "logit_fusion": "Logit-Level Fusion Variant",
          "proposed": "Reliability-Aware Fusion (Proposed)"}
COLORS = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b"]

# Figure 1
fig, ax = plt.subplots(figsize=(11, 4.5))
x = np.arange(len(SETTINGS4)); bw = 0.13
for i, m in enumerate(LABELS):
    vals = [t2[(t2.model == m) & (t2.setting == s)].accuracy.iloc[0] for s in SETTINGS4]
    ax.bar(x + (i - 2.5) * bw, vals, bw, label=LABELS[m], color=COLORS[i])
ax.set_xticks(x, ["Clean", "Noise", "Channel Drop", "Cloud Mask"])
ax.set_ylabel("Classification Accuracy"); ax.set_ylim(0, 1.05)
ax.set_title("Model Accuracy under Optical Degraded Conditions")
ax.legend(fontsize=8); fig.tight_layout()
fig.savefig(f"{FIG_DIR}/figure1_new.png", dpi=300); plt.show()

# Figure 2 (ablation subset)
fig, ax = plt.subplots(figsize=(8.5, 4.5))
for i, m in enumerate(["feature_fusion", "logit_fusion", "proposed"]):
    vals = [t2[(t2.model == m) & (t2.setting == s)].accuracy.iloc[0] for s in SETTINGS4]
    ax.bar(x + (i - 1) * 0.25, vals, 0.25, label=LABELS[m], color=["red", "mediumpurple", "orange"][i])
ax.set_xticks(x, ["Clean", "Noise", "Channel Drop", "Cloud Mask"])
ax.set_ylabel("Classification Accuracy"); ax.set_ylim(0.5, 1.03)
ax.set_title("Ablation Comparison of Fusion Strategies"); ax.legend(); fig.tight_layout()
fig.savefig(f"{FIG_DIR}/figure2_new.png", dpi=300); plt.show()

# Figure 3 (gate weights)
fig, ax = plt.subplots(figsize=(9, 4.2))
xs = np.arange(len(SETTINGS6))
sw = [t34[t34.setting == s].avg_radar_weight.iloc[0] for s in SETTINGS6]
ow = [t34[t34.setting == s].avg_optical_weight.iloc[0] for s in SETTINGS6]
ax.bar(xs - 0.18, sw, 0.36, label="SAR Weight", color="#4472c4")
ax.bar(xs + 0.18, ow, 0.36, label="Optical Weight", color="#70ad47")
ax.axhline(0.5, ls="--", c="gray", lw=1, label="Equal weighting")
ax.set_xticks(xs, ["Clean", "Noise", "Heavy\nNoise", "Channel\nDrop", "Cloud\nMask", "Mixed"])
ax.set_ylabel("Average Reliability Weight")
ax.set_title("Learned Reliability Gate Weights Under Different Optical Conditions")
ax.legend(); fig.tight_layout()
fig.savefig(f"{FIG_DIR}/figure3_new.png", dpi=300); plt.show()

# Figure 4 (per-class F1, three settings)
t5 = pd.read_csv(f"{SAVE_DIR}/new_table5_perclass_f1.csv")
fig, axes = plt.subplots(1, 3, figsize=(12, 3.8), sharey=True)
for ax, s in zip(axes, ["clean", "noise", "heavy_noise"]):
    row = t5[t5.setting == s].iloc[0]
    vals = [row[f"f1_{c}"] for c in CLASS_NAMES]
    ax.bar(CLASS_NAMES, vals, color=["#4472c4", "#70ad47", "#d62728", "#9467bd"])
    ax.axhline(row.macro_f1, ls="--", c="gray", lw=1)
    ax.set_title(s); ax.set_ylim(0, 1.05)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.01, f"{v:.3f}", ha="center", fontsize=7)
axes[0].set_ylabel("Per-Class F1 Score")
fig.suptitle("Per-Class F1 Score by Degradation Setting")
fig.tight_layout(); fig.savefig(f"{FIG_DIR}/figure4_new.png", dpi=300); plt.show()

import re

print("Example SAR filename stems (3 per class):")
by_class = {}
for s1, s2, lbl in pairs:
    by_class.setdefault(lbl, []).append(s1.stem)
for c in CLASS_NAMES:
    for st in by_class[c][:3]:
        print(f"  {c}: {st}")

def spatial_unit(path):
    stem = path.stem
    m = re.search(r"(ROIs\d+_[A-Za-z]+)", stem)
    roi = m.group(1) if m else "noROI"
    m2 = re.search(r"_s[12]_(\d+)_p\d+", stem)          # SEN12MS: ..._s1_<scene>_p<patch>
    if m2:
        scene = m2.group(1)
    else:                                                # fallback: second-to-last number in stem
        nums = re.findall(r"\d+", stem)
        scene = nums[-2] if len(nums) >= 2 else (nums[-1] if nums else "0")
    return f"{roi}_sc{scene}"

unit_df = pd.DataFrame([{"unit": spatial_unit(s1), "label": lbl} for s1, _, lbl in pairs])
print("\nDistinct spatial units:", unit_df.unit.nunique())
print("Units per class:")
display(unit_df.groupby("label").unit.nunique())
print("Samples per unit:")
display(unit_df.unit.value_counts().describe())
print("Unit x class table (first 15):")
display(unit_df.groupby(["unit", "label"]).size().unstack(fill_value=0).head(15))

N_UNITS = unit_df.unit.nunique()
assert N_UNITS >= 20, (f"Only {N_UNITS} spatial units - STOP and send Cell 18 output back "
                       "so the filename parser can be adjusted.")

# Hold out whole scenes totalling ~20% of samples per class.
rng = np.random.default_rng(REP_SEED)
test_units = set()
for c in CLASS_NAMES:
    sub = unit_df[unit_df.label == c].unit.value_counts()
    units = [u for u in sub.index if u not in test_units]
    rng.shuffle(units)
    already = unit_df[(unit_df.label == c) & (unit_df.unit.isin(test_units))].shape[0]
    target, got = 0.20 * sub.sum(), already
    for u in units:
        if got >= target:
            break
        test_units.add(u); got += sub[u]

roi_train = [p for p in pairs if spatial_unit(p[0]) not in test_units]
roi_test = [p for p in pairs if spatial_unit(p[0]) in test_units]
print(f"Spatial-train: {len(roi_train)}  Spatial-test: {len(roi_test)}  held-out scenes: {len(test_units)}")
print("Test class counts:", Counter(l for _, _, l in roi_test))
assert len(roi_train) > 1000 and len(roi_test) > 500, "Degenerate split - send this output back."
assert not ({spatial_unit(p[0]) for p in roi_train} & test_units), "Leakage: unit in both sets!"

trl = DataLoader(Sentinel12PairDataset(roi_train), batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
tel = DataLoader(Sentinel12PairDataset(roi_test), batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

roi_rows = []
for name, epochs, lr in [("optical", 10, 1e-3), ("logit_fusion", 15, 1e-3), ("proposed", 15, 8e-4)]:
    ckpt = f"{SAVE_DIR}/{name}_roisplit.pt"
    m = MODEL_BUILDERS[name]().to(DEVICE)
    if os.path.exists(ckpt):
        m.load_state_dict(torch.load(ckpt, map_location=DEVICE))
        print(f"{name}: loaded ROI-split checkpoint")
    else:
        print(f"\n=== ROI-split training: {name} ===")
        set_all_seeds(REP_SEED)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.AdamW(m.parameters(), lr=lr, weight_decay=1e-4)
        best_score, best_state = -1.0, None
        for epoch in range(1, epochs + 1):
            loss = train_epoch(m, name, trl, optimizer, criterion)
            if name == "proposed":
                evals = {s: evaluate(m, name, tel, s)["accuracy"] for s in SETTINGS4}
                score = sum(evals.values()) / 4
                if score > best_score:
                    best_score = score
                    best_state = {k: v.detach().cpu().clone() for k, v in m.state_dict().items()}
                print(f"{name} epoch={epoch} loss={loss:.4f} score={score:.4f}")
            else:
                print(f"{name} epoch={epoch} loss={loss:.4f}")
        if name == "proposed":
            m.load_state_dict(best_state)
        torch.save(m.state_dict(), ckpt)
    for s in SETTINGS4 + (["heavy_noise", "mixed"] if name == "proposed" else []):
        r = evaluate(m, name, tel, s)
        r.update({"model": name, "setting": s})
        roi_rows.append(r)
        print(name, s, round(r["accuracy"], 4))

pd.DataFrame(roi_rows).to_csv(f"{SAVE_DIR}/roi_split_results.csv", index=False)
print("Saved roi_split_results.csv")

import matplotlib.pyplot as plt

REAL_DIR = f"{SAVE_DIR}/real_cloud_pairs"
os.makedirs(REAL_DIR, exist_ok=True)

# EDIT THIS: one line per site, exactly these class words: agri / barrenland / grassland / urban
TRUE_CLASS = {
    "site1": "urban",
    "site2": "agri",
    "site3": "barrenland",
    "site4": "grassland",
    "site5": "grassland",
    "site6": "agri",
    }

pngs = [p for p in os.listdir(REAL_DIR) if p.lower().endswith(".png")]
assert pngs, f"No PNG files found in {REAL_DIR} - upload them to Drive first."

sites = sorted({p.split("_")[0] for p in pngs})
print("Sites found:", sites)

# Check every site has both files before doing anything
missing = []
for site in sites:
    for suffix in ["s1", "s2"]:
        if f"{site}_{suffix}.png" not in pngs:
            missing.append(f"{site}_{suffix}.png")
assert not missing, f"Missing files: {missing} - check the exact names in Drive."

model = models["proposed"]   # from Cell 12; if not loaded, run Cell 12 first
model.eval()

fig, axes = plt.subplots(2, len(sites), figsize=(2.4 * len(sites), 5.2), squeeze=False)
results = []
with torch.no_grad():
    for k, site in enumerate(sites):
        s1_img = Image.open(f"{REAL_DIR}/{site}_s1.png")
        s2_img = Image.open(f"{REAL_DIR}/{site}_s2.png")

        r = pil_to_tensor(s1_img, "L").unsqueeze(0).to(DEVICE)
        o = pil_to_tensor(s2_img, "RGB").unsqueeze(0).to(DEVICE)

        logits, w, rl, ol = model(r, o, return_all=True)
        pred = CLASS_NAMES[logits.argmax(1).item()]
        w_sar = w[0, 0].item()
        true = TRUE_CLASS.get(site, "?")
        results.append({"site": site, "true": true, "pred": pred,
                        "w_sar": round(w_sar, 3),
                        "optical_branch_pred": CLASS_NAMES[ol.argmax(1).item()],
                        "sar_branch_pred": CLASS_NAMES[rl.argmax(1).item()]})

        color = "green" if pred == true else ("black" if true == "?" else "red")
        axes[0, k].imshow(np.array(s2_img.convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE))))
        axes[0, k].set_title(f"{site}\ntrue: {true}  pred: {pred}\nw_SAR = {w_sar:.2f}",
                             fontsize=9, color=color)
        axes[1, k].imshow(np.array(s1_img.convert("L").resize((IMAGE_SIZE, IMAGE_SIZE))), cmap="gray")
        for ax in [axes[0, k], axes[1, k]]:
            ax.axis("off")

axes[0, 0].set_ylabel("Sentinel-2 (cloudy)")
axes[1, 0].set_ylabel("Sentinel-1 SAR")
fig.suptitle("Proposed model on real cloud-contaminated Sentinel-2 patches", fontsize=11)
fig.tight_layout()
fig.savefig(f"{FIG_DIR}/real_cloud_qualitative.png", dpi=300, bbox_inches="tight")
plt.show()

res_df = pd.DataFrame(results)
display(res_df)
res_df.to_csv(f"{SAVE_DIR}/real_cloud_results.csv", index=False)
print("Saved figure and real_cloud_results.csv")